### PR TITLE
add xray variables to the list of variables that change at execution time

### PR DESCRIPTION
**Pull request by tobowers**
Now that lambda supports xray active tracing, there are a few more environment variables that can change at execution time.

### CODE REVIEW

**Comment by fsenart** [comment]
Hi @tobowers,
First of all, thank you very much for your contribution.
As you've noticed the variables we update before each execution are the those subject to change during the lifetime of a lambda function. Other variables, if changed, *reset* the lambda.
In the case of XRay, I agree that `_X_AMZN_TRACE_ID` is the one that changes every time, but `AWS_XRAY_DAEMON_ADDRESS` does not changes over the lifetime (aws official sdks read this variables [once](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/segment_emitter.js#L100) during init) and `AWS_XRAY_CONTEXT_MISSING` is set to a default value by lambda and can be overridden by the user, in which case it resets the Lambda.

**Comment by tobowers** [comment]
@fsenart updated

**Comment by tobowers** [comment]
Thanks! When does this end up in the :latest tag for the docker image?

**Comment by fsenart** [comment]
Thank you @tobowers. The repo is linked to Docker Hub so that each commit produces an automated build. In a few minutes the new version will be available so you can pull it :wink:

**Comment by fsenart** [comment]
https://hub.docker.com/r/eawsy/aws-lambda-go-shim/builds/

**Comment by fsenart** [comment]
@tobowers if you are playing with XRay on Lambda it may be of interest https://github.com/aws/aws-xray-sdk-go/issues/16

**Comment by tobowers** [comment]
ah thanks! Yeah, I had to hack the sdk to use a global variable... which was less than ideal

**Comment by nzoschke** [comment]
@tbowers can you share how you got X-ray working with the shim? I’m not seeing my segments show up anywhere

**Comment by cristim** [comment]
@xlr-8 how did you set it up with AutoSpotting? 

This may be of interest for https://github.com/cristim/autospotting/issues/169

**Comment by xlr-8** [comment]
Sorry I haven't taken thorough notes as it wasn't up to my expectations. As of Go in Lambda is not being yet officially released, the X-Ray support should be very limited (only Lambda + Lambda function displayed in the service map) - AWS case confirmed my thoughts.

Otherwise if I recall correctly, I:
1. Activated through the console http://docs.aws.amazon.com/xray/latest/devguide/xray-services-lambda.html - however it was for me in "Debugging and error handling" tick "Enable active tracing"
1. Added the configuration from https://github.com/aws/aws-xray-sdk-go
1. Added respective policies (2 to 3) to the IAM role

And that was it, if you do have interesting result (detailed methods & so on) please let me know.

**Comment by tobowers** [comment]
I had to hack up the xray go sdk: https://github.com/aws/aws-xray-sdk-go/compare/master...QuorumControl:master

Meat of the changes (besides find/replace of aws -> QuorumControl) is:

https://github.com/aws/aws-xray-sdk-go/compare/master...QuorumControl:master#diff-87ebca28bc1c1ca7a9015f572319d2c6R26

and

https://github.com/aws/aws-xray-sdk-go/compare/master...QuorumControl:master#diff-2b29baad30e85be1aee3a32a9cbdbc2bR87

**Pull request merged**
