### PR TITLE
Add instructions to create a role

### PR DESCRIPTION
**Pull request by tleyden**
On my first attempt to follow README, I got:

> An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.

and thought I did something wrong or missed a step, had to google .. and the above worked for me!

### CODE REVIEW

**Comment by fsenart** [comment]
@tleyden in fact when you create your first Lambda, if you use the AWS console, the `basic_execution_role` is created for you.  
Your PR is a very good addition as it allows to anyone to fully deploy the Lambda without any prior (supposed) config.

I've left you a few comments on the code :wink:

**Comment by fsenart** [comment]
You should also update the TOC in your PR :wink:

**Comment by tleyden** [comment]
Thanks!  All of these changes make sense, thanks for the explanations.  Pushed up a few commits.

**Comment by fsenart** [comment]
Thanks a lot for your PR :wink:

**Pull request merged**
